#!/bin/bash -e

cd $( dirname "${BASH_SOURCE[0]}" )

if [[ -z "$1" ]]; then
  echo "Slack Token is required as the first argument"
  exit 1
fi

docker build -t slack-status-time . > /dev/null 2>&1

docker run -e "SLACK_TOKEN=$1" -e "TZ=${TZ:-America/New_York}" slack-status-time
